In [1]:
import numpy as np
import pandas as pd
from starfish.plot import *

In [2]:
from starfish.set import settings
settings.var_name.remove('N_eff')
settings.cosmo_num-=1

In [3]:
def var_filter(fisher,lcdm,neff_fixed):
    df=fisher.copy()
    if lcdm:
        df=df.drop('w0',axis=0)
        df=df.drop('w0',axis=1)
        df=df.drop('wa',axis=0)
        df=df.drop('wa',axis=1)
    if neff_fixed:
        df=df.drop('N_eff',axis=0)
        df=df.drop('N_eff',axis=1)

    return df

# nuisance parameters of different tracers/surveys should be independent of each other

In [4]:
DESI_multi=var_filter(pd.read_excel('../data/DESI_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
cov=pd.DataFrame(np.linalg.inv(DESI_multi.values),index=DESI_multi.index,columns=DESI_multi.columns)
DESI_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [5]:
JPAS_multi=var_filter(pd.read_excel('../data/jpas_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
cov=pd.DataFrame(np.linalg.inv(JPAS_multi.values),index=JPAS_multi.index,columns=JPAS_multi.columns)
JPAS_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [6]:
PFS_ELG=var_filter(pd.read_excel('../data/PFS/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
cov=pd.DataFrame(np.linalg.inv(PFS_ELG.values),index=PFS_ELG.index,columns=PFS_ELG.columns)
PFS_ELG_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

# SO + LiteBIRD + DESI multitracer

In [7]:
cmb_fisher=var_filter(pd.read_excel('../data/CMB/all.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
cmb_fisher

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,tau,w0,wa
omega_m0,2.147834e+08,-7.541764e+08,1.650643e+08,-4.990171e+06,-6.793243e+07,-1.477549e+07,5.285179e+07,1.526209e+06,-43858.240484
omega_b0,-7.541764e+08,3.045160e+09,-5.322297e+08,3.220158e+07,2.430377e+08,5.176599e+07,-1.876023e+08,-7.272188e+06,-347201.477824
h,1.650643e+08,-5.322297e+08,1.371531e+08,-2.256316e+06,-4.712226e+07,-9.843028e+06,3.669686e+07,3.577965e+06,651471.937061
n_s,-4.990171e+06,3.220158e+07,-2.256316e+06,1.126557e+06,1.775017e+06,3.317576e+05,-1.355804e+06,-1.478760e+05,-28437.056773
sigma_8,-6.793243e+07,2.430377e+08,-4.712226e+07,1.775017e+06,2.652467e+07,6.277010e+06,-2.060786e+07,2.218886e+06,778936.336670
m_nu,-1.477549e+07,5.176599e+07,-9.843028e+06,3.317576e+05,6.277010e+06,1.541394e+06,-4.902868e+06,7.908602e+05,256559.839365
tau,5.285179e+07,-1.876023e+08,3.669686e+07,-1.355804e+06,-2.060786e+07,-4.902868e+06,1.635373e+07,-1.773297e+06,-619360.547727
w0,1.526209e+06,-7.272188e+06,3.577965e+06,-1.478760e+05,2.218886e+06,7.908602e+05,-1.773297e+06,1.552171e+06,435641.832226
wa,-4.385824e+04,-3.472015e+05,6.514719e+05,-2.843706e+04,7.789363e+05,2.565598e+05,-6.193605e+05,4.356418e+05,123324.164109

In [8]:
cmb_cov=pd.DataFrame(np.linalg.inv(cmb_fisher.values),index=cmb_fisher.index,columns=cmb_fisher.columns)
cmb_cov_marg=cmb_cov.drop('tau',axis=0)
cmb_cov_marg=cmb_cov_marg.drop('tau',axis=1)
cmb_fisher_marg=pd.DataFrame(np.linalg.inv(cmb_cov_marg),index=settings.var_name,columns=settings.var_name)
cmb_fisher_marg

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,w0,wa
omega_m0,4.397760e+07,-1.478854e+08,4.646782e+07,-6.085000e+05,-1.332188e+06,1.069536e+06,7.257129e+06,1.957784e+06
omega_b0,-1.478854e+08,8.930742e+08,-1.112605e+08,1.664844e+07,6.633934e+06,-4.477407e+06,-2.761462e+07,-7.452216e+06
h,4.646782e+07,-1.112605e+08,5.480743e+07,7.860325e+05,-8.793651e+05,1.158735e+06,7.557145e+06,2.041283e+06
n_s,-6.085000e+05,1.664844e+07,7.860325e+05,1.014154e+06,6.652502e+04,-7.471398e+04,-2.948910e+05,-7.978507e+04
sigma_8,-1.332188e+06,6.633934e+06,-8.793651e+05,6.652502e+04,5.560451e+05,9.874888e+04,-1.570282e+04,-1.539849e+03
m_nu,1.069536e+06,-4.477407e+06,1.158735e+06,-7.471398e+04,9.874888e+04,7.150858e+04,2.592236e+05,7.087480e+04
w0,7.257129e+06,-2.761462e+07,7.557145e+06,-2.948910e+05,-1.570282e+04,2.592236e+05,1.359885e+06,3.684822e+05
wa,1.957784e+06,-7.452216e+06,2.041283e+06,-7.978507e+04,-1.539849e+03,7.087480e+04,3.684822e+05,9.986728e+04

In [9]:
fisher1_combined=DESI_multi_valid+cmb_fisher_marg
fisher1_combined.to_excel('../data/combined/cmb+dmul-w0wacdm-fixed.xlsx')
cov1_combined=pd.DataFrame(np.linalg.inv(fisher1_combined),index=fisher1_combined.index,columns=fisher1_combined.columns)
cov1_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,w0,wa
omega_m0,5.084541e-06,5.122767e-07,-3.407647e-06,-6.677331e-07,-8.079490e-06,0.000050,0.000030,-0.000137
omega_b0,5.122767e-07,1.061126e-07,-6.717631e-07,5.813921e-09,-6.560139e-07,-0.000002,0.000007,-0.000013
h,-3.407647e-06,-6.717631e-07,4.488875e-06,-4.499717e-07,4.226507e-06,0.000010,-0.000044,0.000080
n_s,-6.677331e-07,5.813921e-09,-4.499717e-07,2.449508e-06,6.879043e-08,-0.000013,0.000010,-0.000004
sigma_8,-8.079490e-06,-6.560139e-07,4.226507e-06,6.879043e-08,2.266487e-05,-0.000151,-0.000065,0.000372
m_nu,5.048918e-05,-1.599190e-06,9.997186e-06,-1.270552e-05,-1.513210e-04,0.001675,-0.000026,-0.002413
w0,2.966394e-05,6.858001e-06,-4.417428e-05,1.022383e-05,-6.545486e-05,-0.000026,0.000825,-0.002182
wa,-1.373935e-04,-1.255897e-05,8.044260e-05,-4.131191e-06,3.719624e-04,-0.002413,-0.002182,0.009869

In [10]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 2.3e-03
-- omega_b0: 3.3e-04
--        h: 2.1e-03
--      n_s: 1.6e-03
--  sigma_8: 4.8e-03
--     m_nu: 4.1e-02
--       w0: 2.9e-02
--       wa: 9.9e-02

# SO + LiteBIRD + DESI multitracer

In [11]:
fisher2=pd.DataFrame(JPAS_multi_valid+PFS_ELG_valid,index=settings.var_name,columns=settings.var_name)
fisher2.to_excel('../data/combined/pelg+jmul-w0wacdm-fixed.xlsx')

In [12]:
fisher2_combined=JPAS_multi_valid+PFS_ELG_valid+cmb_fisher_marg
fisher2_combined.to_excel('../data/combined/cmb+pelg+jmul-w0wacdm-fixed.xlsx')
cov2_combined=pd.DataFrame(np.linalg.inv(fisher2_combined),index=fisher2_combined.index,columns=fisher2_combined.columns)
cov2_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,w0,wa
omega_m0,8.560980e-06,8.267305e-07,-5.495311e-06,-1.247078e-06,-1.404037e-05,0.000096,0.000078,-0.000349
omega_b0,8.267305e-07,1.715739e-07,-1.093050e-06,4.681372e-08,-1.276703e-06,-0.000002,0.000012,-0.000026
h,-5.495311e-06,-1.093050e-06,7.176663e-06,-6.408853e-07,8.376081e-06,0.000008,-0.000082,0.000176
n_s,-1.247078e-06,4.681372e-08,-6.408853e-07,2.700018e-06,6.749674e-07,-0.000028,0.000013,0.000013
sigma_8,-1.404037e-05,-1.276703e-06,8.376081e-06,6.749674e-07,3.270297e-05,-0.000217,-0.000152,0.000725
m_nu,9.554743e-05,-1.572377e-06,7.597510e-06,-2.806874e-05,-2.174275e-04,0.002682,0.000486,-0.005867
w0,7.759204e-05,1.237567e-05,-8.187288e-05,1.346291e-05,-1.521028e-04,0.000486,0.001886,-0.006217
wa,-3.488473e-04,-2.557034e-05,1.756381e-04,1.337682e-05,7.249690e-04,-0.005867,-0.006217,0.028463

In [13]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov2_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 2.9e-03
-- omega_b0: 4.1e-04
--        h: 2.7e-03
--      n_s: 1.6e-03
--  sigma_8: 5.7e-03
--     m_nu: 5.2e-02
--       w0: 4.3e-02
--       wa: 1.7e-01