In [1]:
import numpy as np
import pandas as pd
from starfish.plot import *

In [2]:
from starfish.set import settings
settings.cosmo_value

[0.32, 0.049, 0.67, 0.96, 0.81, 0.06, 3.044, -1, 0]

In [3]:
def var_filter(fisher,lcdm,neff_fixed):
    df=fisher.copy()
    if lcdm:
        df=df.drop('w0',axis=0)
        df=df.drop('w0',axis=1)
        df=df.drop('wa',axis=0)
        df=df.drop('wa',axis=1)
    if neff_fixed:
        df=df.drop('N_eff',axis=0)
        df=df.drop('N_eff',axis=1)

    return df

# nuisance parameters of different tracers/surveys should be independent of each other

In [4]:
DESI_multi=var_filter(pd.read_excel('../data/DESI_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(DESI_multi.values),index=DESI_multi.index,columns=DESI_multi.columns)
DESI_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

# SO + LiteBIRD + DESI multitracer

In [5]:
cmb_fisher=var_filter(pd.read_excel('../data/CMB/all.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cmb_fisher

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,tau,w0,wa
omega_m0,2.113157e+08,-7.391461e+08,1.626544e+08,-4.834304e+06,-6.693431e+07,-1.457689e+07,-7.508163e+06,5.208923e+07,1.425684e+06,-64524.040323
omega_b0,-7.391461e+08,2.972795e+09,-5.230892e+08,3.136963e+07,2.383183e+08,5.078972e+07,2.516905e+07,-1.839974e+08,-7.019564e+06,-309843.766393
h,1.626544e+08,-5.230892e+08,1.351853e+08,-2.179861e+06,-4.655793e+07,-9.745314e+06,-6.396045e+06,3.626849e+07,3.441885e+06,618290.947153
n_s,-4.834304e+06,3.136963e+07,-2.179861e+06,1.112812e+06,1.717749e+06,3.189561e+05,1.152375e+05,-1.311012e+06,-1.495027e+05,-29267.899603
sigma_8,-6.693431e+07,2.383183e+08,-4.655793e+07,1.717749e+06,2.614606e+07,6.191752e+06,1.849826e+06,-2.031985e+07,2.201249e+06,771688.957096
m_nu,-1.457689e+07,5.078972e+07,-9.745314e+06,3.189561e+05,6.191752e+06,1.521177e+06,3.498935e+05,-4.837493e+06,7.818822e+05,253566.528706
N_eff,-7.508163e+06,2.516905e+07,-6.396045e+06,1.152375e+05,1.849826e+06,3.498935e+05,3.262999e+05,-1.436583e+06,-3.319948e+05,-77468.971284
tau,5.208923e+07,-1.839974e+08,3.626849e+07,-1.311012e+06,-2.031985e+07,-4.837493e+06,-1.436583e+06,1.613244e+07,-1.759261e+06,-613654.679077
w0,1.425684e+06,-7.019564e+06,3.441885e+06,-1.495027e+05,2.201249e+06,7.818822e+05,-3.319948e+05,-1.759261e+06,1.524648e+06,428067.764406
wa,-6.452404e+04,-3.098438e+05,6.182909e+05,-2.926790e+04,7.716890e+05,2.535665e+05,-7.746897e+04,-6.136547e+05,4.280678e+05,121223.935866

In [6]:
cmb_cov=pd.DataFrame(np.linalg.inv(cmb_fisher.values),index=cmb_fisher.index,columns=cmb_fisher.columns)
cmb_cov_marg=cmb_cov.drop('tau',axis=0)
cmb_cov_marg=cmb_cov_marg.drop('tau',axis=1)
cmb_fisher_marg=pd.DataFrame(np.linalg.inv(cmb_cov_marg),index=settings.var_name,columns=settings.var_name)
cmb_fisher_marg

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,4.312745e+07,-1.450462e+08,4.554887e+07,-6.012452e+05,-1.324571e+06,1.042646e+06,-2.869655e+06,7.106071e+06,1.916874e+06
omega_b0,-1.450462e+08,8.742251e+08,-1.094315e+08,1.641698e+07,6.561623e+06,-4.383950e+06,8.784214e+06,-2.708469e+07,-7.308838e+06
h,4.554887e+07,-1.094315e+08,5.364748e+07,7.675169e+05,-8.754294e+05,1.130196e+06,-3.166362e+06,7.397003e+06,1.997892e+06
n_s,-6.012452e+05,1.641698e+07,7.675169e+05,1.006272e+06,6.644545e+04,-7.416530e+04,-1.507177e+03,-2.924700e+05,-7.913687e+04
sigma_8,-1.324571e+06,6.561623e+06,-8.754294e+05,6.644545e+04,5.518892e+05,9.861775e+04,4.035742e+04,-1.465311e+04,-1.248684e+03
m_nu,1.042646e+06,-4.383950e+06,1.130196e+06,-7.416530e+04,9.861775e+04,7.060115e+04,-8.088178e+04,2.543484e+05,6.955536e+04
N_eff,-2.869655e+06,8.784214e+06,-3.166362e+06,-1.507177e+03,4.035742e+04,-8.088178e+04,1.983733e+05,-4.886557e+05,-1.321145e+05
w0,7.106071e+06,-2.708469e+07,7.397003e+06,-2.924700e+05,-1.465311e+04,2.543484e+05,-4.886557e+05,1.332799e+06,3.611481e+05
wa,1.916874e+06,-7.308838e+06,1.997892e+06,-7.913687e+04,-1.248684e+03,6.955536e+04,-1.321145e+05,3.611481e+05,9.788141e+04

In [7]:
fisher1_combined=DESI_multi_valid+cmb_fisher_marg
fisher1_combined.to_excel('../data/combined/cmb+dmul-w0wacdm-free.xlsx')
cov1_combined=pd.DataFrame(np.linalg.inv(fisher1_combined),index=fisher1_combined.index,columns=fisher1_combined.columns)
cov1_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,6.886332e-06,4.510854e-07,-2.375197e-06,1.070085e-06,-8.385586e-06,0.000071,0.000045,0.000040,-0.000190
omega_b0,4.510854e-07,1.085829e-07,-7.083838e-07,-5.551421e-08,-6.507802e-07,-0.000002,-0.000002,0.000007,-0.000011
h,-2.375197e-06,-7.083838e-07,5.091577e-06,5.562574e-07,4.103467e-06,0.000022,0.000026,-0.000038,0.000051
n_s,1.070085e-06,-5.551421e-08,5.562574e-07,4.150124e-06,-1.874525e-07,0.000007,0.000044,0.000020,-0.000055
sigma_8,-8.385586e-06,-6.507802e-07,4.103467e-06,-1.874525e-07,2.300520e-05,-0.000156,-0.000006,-0.000068,0.000384
m_nu,7.129399e-05,-2.300582e-06,2.172869e-05,7.267674e-06,-1.561089e-04,0.001922,0.000516,0.000098,-0.003034
N_eff,4.525266e-05,-1.567818e-06,2.622285e-05,4.392345e-05,-6.134144e-06,0.000516,0.001146,0.000267,-0.001312
w0,4.036941e-05,6.513145e-06,-3.812321e-05,2.047748e-05,-6.757096e-05,0.000098,0.000267,0.000889,-0.002499
wa,-1.901972e-04,-1.082060e-05,5.068098e-05,-5.472071e-05,3.835907e-04,-0.003034,-0.001312,-0.002499,0.011442

In [8]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 2.6e-03
-- omega_b0: 3.3e-04
--        h: 2.3e-03
--      n_s: 2.0e-03
--  sigma_8: 4.8e-03
--     m_nu: 4.4e-02
--    N_eff: 3.4e-02
--       w0: 3.0e-02
--       wa: 1.1e-01