In [1]:
import numpy as np
import pandas as pd

In [2]:
def var_filter(fisher,lcdm,neff_fixed):
    df=fisher.copy()
    if lcdm:
        df=df.drop('w0',axis=0)
        df=df.drop('w0',axis=1)
        df=df.drop('wa',axis=0)
        df=df.drop('wa',axis=1)
    if neff_fixed:
        df=df.drop('N_eff',axis=0)
        df=df.drop('N_eff',axis=1)

    return df

# lcdm

# $N_\mathrm{eff}$ fixed

In [3]:
CMB_fixed=var_filter(pd.read_excel('./CMB/all.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
cmb_cov_fixed=pd.DataFrame(np.linalg.inv(CMB_fixed.values),index=CMB_fixed.index,columns=CMB_fixed.columns)
cmb_cov_marg_fixed=cmb_cov_fixed.drop('tau',axis=0)
cmb_cov_marg_fixed=cmb_cov_marg_fixed.drop('tau',axis=1)
CMB_fixed=pd.DataFrame(np.linalg.inv(cmb_cov_marg_fixed.values),index=cmb_cov_marg_fixed.index,columns=cmb_cov_marg_fixed.columns)
ELG_fixed=var_filter(pd.read_excel('./ELG/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
LRG_fixed=var_filter(pd.read_excel('./LRG/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
QSO_fixed=var_filter(pd.read_excel('./QSO/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
PFS_fixed=var_filter(pd.read_excel('./PFS/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
multitracer_fixed=var_filter(pd.read_excel('./jpas_all/valid.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
survey_only_fixed=pd.read_excel('./combined/pelg+jmul-lcdm-fixed.xlsx',header=0,index_col=0)
DESI_fixed=var_filter(pd.read_excel('./DESI_all/valid.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
best_fixed=pd.read_excel('./combined/cmb+pelg+jmul-lcdm-fixed.xlsx',header=0,index_col=0)
gold_fixed=pd.read_excel('./combined/cmb+dmul-lcdm-fixed.xlsx',header=0,index_col=0)

In [4]:
orders=[r'$h$',r'$\Omega_\mathrm{m,0}$',r'$\Omega_\mathrm{b,0}$',r'$\sigma_8$',r'$n_\mathrm{s}$',r'$\sum m_\nu\;[\mathrm{eV}]$',r'$N_\mathrm{eff}$']
names=['h','omega_m0','omega_b0','sigma_8','n_s','m_nu',]
err_fixed=[]
fishers_fixed=[CMB_fixed,ELG_fixed,LRG_fixed,QSO_fixed,PFS_fixed,multitracer_fixed,survey_only_fixed,DESI_fixed,best_fixed,gold_fixed]
for f in fishers_fixed:
    cov=pd.DataFrame(np.linalg.inv(f.values),index=f.index,columns=f.columns).iloc[:len(orders),:len(orders)]
    e=[]
    for i,index in enumerate(names):
        e.append(np.sqrt(cov.loc[index,index]))
    err_fixed.append(np.array(e))
err_fixed=np.stack(err_fixed,axis=0)

In [5]:
labels=['CMB','J-PAS ELG','J-PAS LRG','J-PAS QSO','PFS ELG','J-PAS Multitracer','J-PAS Multitracer + PFS ELG','DESI Multitracer','CMB + J-PAS Multitracer\n+ PFS ELG','CMB + DESI Multitracer']
df_fixed=pd.DataFrame(err_fixed,index=labels,columns=names)
df_fixed

,h,omega_m0,omega_b0,sigma_8,n_s,m_nu
CMB,0.006768,0.008942,0.000973,0.010085,0.001927,0.050220
J-PAS ELG,0.013176,0.014649,0.005714,0.020619,0.026350,0.268775
J-PAS LRG,0.019501,0.022832,0.008106,0.034891,0.047364,0.374461
J-PAS QSO,0.015740,0.031036,0.008814,0.043384,0.046786,0.356000
PFS ELG,0.015160,0.013098,0.006185,0.037094,0.046400,0.552865
J-PAS Multitracer,0.007671,0.007344,0.003286,0.014947,0.015483,0.204577
J-PAS Multitracer + PFS ELG,0.006320,0.004826,0.002637,0.013441,0.011835,0.183607
DESI Multitracer,0.005742,0.003803,0.002285,0.013850,0.018085,0.214545
CMB + J-PAS Multitracer\n+ PFS ELG,0.001587,0.002073,0.000249,0.003843,0.001503,0.016822
CMB + DESI Multitracer,0.001341,0.001781,0.000204,0.002805,0.001488,0.013090

In [6]:
df_fixed.to_excel('./numbers/lcdm-fixed.xlsx')

# $N_\mathrm{eff}$ free

In [7]:
CMB_free=var_filter(pd.read_excel('./CMB/all.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
cmb_cov_free=pd.DataFrame(np.linalg.inv(CMB_free.values),index=CMB_free.index,columns=CMB_free.columns)
cmb_cov_marg_free=cmb_cov_free.drop('tau',axis=0)
cmb_cov_marg_free=cmb_cov_marg_free.drop('tau',axis=1)
CMB_free=pd.DataFrame(np.linalg.inv(cmb_cov_marg_free.values),index=cmb_cov_marg_free.index,columns=cmb_cov_marg_free.columns)
ELG_free=var_filter(pd.read_excel('./ELG/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
LRG_free=var_filter(pd.read_excel('./LRG/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
QSO_free=var_filter(pd.read_excel('./QSO/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
PFS_free=var_filter(pd.read_excel('./PFS/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
multitracer_free=var_filter(pd.read_excel('./jpas_all/valid.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
survey_only_free=pd.read_excel('./combined/pelg+jmul-lcdm-free.xlsx',header=0,index_col=0)
DESI_free=var_filter(pd.read_excel('./DESI_all/valid.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
best_free=pd.read_excel('./combined/cmb+pelg+jmul-lcdm-free.xlsx',header=0,index_col=0)
gold_free=pd.read_excel('./combined/cmb+dmul-lcdm-free.xlsx',header=0,index_col=0)

In [8]:
names=['h','omega_m0','omega_b0','sigma_8','n_s','m_nu','N_eff',]
err_free=[]
fishers_free=[CMB_free,ELG_free,LRG_free,QSO_free,PFS_free,multitracer_free,survey_only_free,DESI_free,best_free,gold_free]
for f in fishers_free:
    cov=pd.DataFrame(np.linalg.inv(f.values),index=f.index,columns=f.columns).iloc[:len(orders),:len(orders)]
    e=[]
    for i,index in enumerate(names):
        e.append(np.sqrt(cov.loc[index,index]))
    err_free.append(np.array(e))
err_free=np.stack(err_free,axis=0)

In [9]:
labels=['CMB','J-PAS ELG','J-PAS LRG','J-PAS QSO','PFS ELG','J-PAS Multitracer','J-PAS Multitracer + PFS ELG','DESI Multitracer','CMB + J-PAS Multitracer\n+ PFS ELG','CMB + DESI Multitracer']
df_free=pd.DataFrame(err_free,index=labels,columns=names)
df_free

,h,omega_m0,omega_b0,sigma_8,n_s,m_nu,N_eff
CMB,0.007932,0.009265,0.001100,0.011241,0.003306,0.051426,0.048279
J-PAS ELG,0.019821,0.015171,0.005720,0.034881,0.026375,0.413169,0.744878
J-PAS LRG,0.022938,0.028295,0.008953,0.044141,0.052415,0.523792,1.029796
J-PAS QSO,0.045694,0.034550,0.009191,0.083359,0.068014,0.727865,2.344445
PFS ELG,0.034885,0.015692,0.006359,0.066768,0.065194,0.672689,1.769438
J-PAS Multitracer,0.012765,0.008393,0.003400,0.025124,0.016086,0.297057,0.585492
J-PAS Multitracer + PFS ELG,0.011536,0.006007,0.002719,0.023100,0.012538,0.269118,0.531678
DESI Multitracer,0.008004,0.004619,0.002525,0.017475,0.020678,0.227722,0.413243
CMB + J-PAS Multitracer\n+ PFS ELG,0.002139,0.002087,0.000285,0.004055,0.002043,0.017184,0.033876
CMB + DESI Multitracer,0.001654,0.001929,0.000220,0.003063,0.001918,0.013787,0.031527

In [10]:
df_free.to_excel('./numbers/lcdm-free.xlsx')

# w0wacdm

# $N_\mathrm{eff}$ fixed

In [11]:
CMB_fixed=var_filter(pd.read_excel('./CMB/all.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
cmb_cov_fixed=pd.DataFrame(np.linalg.inv(CMB_fixed.values),index=CMB_fixed.index,columns=CMB_fixed.columns)
cmb_cov_marg_fixed=cmb_cov_fixed.drop('tau',axis=0)
cmb_cov_marg_fixed=cmb_cov_marg_fixed.drop('tau',axis=1)
CMB_fixed=pd.DataFrame(np.linalg.inv(cmb_cov_marg_fixed.values),index=cmb_cov_marg_fixed.index,columns=cmb_cov_marg_fixed.columns)
ELG_fixed=var_filter(pd.read_excel('./ELG/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
LRG_fixed=var_filter(pd.read_excel('./LRG/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
QSO_fixed=var_filter(pd.read_excel('./QSO/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
PFS_fixed=var_filter(pd.read_excel('./PFS/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
multitracer_fixed=var_filter(pd.read_excel('./jpas_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
survey_only_fixed=pd.read_excel('./combined/pelg+jmul-w0wacdm-fixed.xlsx',header=0,index_col=0)
DESI_fixed=var_filter(pd.read_excel('./DESI_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
best_fixed=pd.read_excel('./combined/cmb+pelg+jmul-w0wacdm-fixed.xlsx',header=0,index_col=0)
gold_fixed=pd.read_excel('./combined/cmb+dmul-w0wacdm-fixed.xlsx',header=0,index_col=0)

In [12]:
orders=[r'$h$',r'$\Omega_\mathrm{m,0}$',r'$\Omega_\mathrm{b,0}$',r'$\sigma_8$',r'$n_\mathrm{s}$',r'$\sum m_\nu\;[\mathrm{eV}]$',r'$N_\mathrm{eff}$',r'$w_0$',r'$w_a$']
names=['h','omega_m0','omega_b0','sigma_8','n_s','m_nu','w0','wa']
err_fixed=[]
fishers_fixed=[CMB_fixed,ELG_fixed,LRG_fixed,QSO_fixed,PFS_fixed,multitracer_fixed,survey_only_fixed,DESI_fixed,best_fixed,gold_fixed]
for f in fishers_fixed:
    cov=pd.DataFrame(np.linalg.inv(f.values),index=f.index,columns=f.columns).iloc[:len(orders),:len(orders)]
    e=[]
    for i,index in enumerate(names):
        e.append(np.sqrt(cov.loc[index,index]))
    err_fixed.append(np.array(e))
err_fixed=np.stack(err_fixed,axis=0)

In [13]:
labels=['CMB','J-PAS ELG','J-PAS LRG','J-PAS QSO','PFS ELG','J-PAS Multitracer','J-PAS Multitracer + PFS ELG','DESI Multitracer','CMB + J-PAS Multitracer\n+ PFS ELG','CMB + DESI Multitracer']
df_fixed=pd.DataFrame(err_fixed,index=labels,columns=names)
df_fixed

,h,omega_m0,omega_b0,sigma_8,n_s,m_nu,w0,wa
CMB,0.081349,0.077173,0.011905,0.072050,0.001982,0.134371,0.546102,1.468748
J-PAS ELG,0.020893,0.033775,0.008673,0.024416,0.042226,0.296189,0.149992,0.813091
J-PAS LRG,0.035128,0.046103,0.011897,0.039931,0.066377,0.425011,0.203446,1.094021
J-PAS QSO,0.019747,0.135437,0.028200,0.122710,0.115561,0.401308,1.141797,3.371027
PFS ELG,0.015854,0.034300,0.008423,0.045631,0.054860,0.610892,0.274993,1.065883
J-PAS Multitracer,0.010073,0.013725,0.003982,0.017888,0.018477,0.216495,0.102488,0.471822
J-PAS Multitracer + PFS ELG,0.007245,0.011423,0.003226,0.016097,0.014666,0.196301,0.091423,0.402913
DESI Multitracer,0.007199,0.009299,0.002619,0.015143,0.020303,0.225564,0.045846,0.268027
CMB + J-PAS Multitracer\n+ PFS ELG,0.002694,0.002945,0.000419,0.005859,0.001659,0.052439,0.043673,0.169989
CMB + DESI Multitracer,0.002119,0.002258,0.000326,0.004793,0.001570,0.041101,0.028756,0.099692

In [14]:
df_fixed.to_excel('./numbers/w0wacdm-fixed.xlsx')

# $N_\mathrm{eff}$ free

In [15]:
CMB_free=var_filter(pd.read_excel('./CMB/all.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cmb_cov_free=pd.DataFrame(np.linalg.inv(CMB_free.values),index=CMB_free.index,columns=CMB_free.columns)
cmb_cov_marg_free=cmb_cov_free.drop('tau',axis=0)
cmb_cov_marg_free=cmb_cov_marg_free.drop('tau',axis=1)
CMB_free=pd.DataFrame(np.linalg.inv(cmb_cov_marg_free.values),index=cmb_cov_marg_free.index,columns=cmb_cov_marg_free.columns)
ELG_free=var_filter(pd.read_excel('./ELG/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
LRG_free=var_filter(pd.read_excel('./LRG/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
QSO_free=var_filter(pd.read_excel('./QSO/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
PFS_free=var_filter(pd.read_excel('./PFS/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
multitracer_free=var_filter(pd.read_excel('./jpas_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
survey_only_free=pd.read_excel('./combined/pelg+jmul-w0wacdm-free.xlsx',header=0,index_col=0)
DESI_free=var_filter(pd.read_excel('./DESI_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
best_free=pd.read_excel('./combined/cmb+pelg+jmul-w0wacdm-free.xlsx',header=0,index_col=0)
gold_free=pd.read_excel('./combined/cmb+dmul-w0wacdm-free.xlsx',header=0,index_col=0)

In [16]:
orders=[r'$h$',r'$\Omega_\mathrm{m,0}$',r'$\Omega_\mathrm{b,0}$',r'$\sigma_8$',r'$n_\mathrm{s}$',r'$\sum m_\nu\;[\mathrm{eV}]$',r'$N_\mathrm{eff}$',r'$w_0$',r'$w_a$']
names=['h','omega_m0','omega_b0','sigma_8','n_s','m_nu','N_eff','w0','wa']
err_free=[]
fishers_free=[CMB_free,ELG_free,LRG_free,QSO_free,PFS_free,multitracer_free,survey_only_free,DESI_free,best_free,gold_free]
for f in fishers_free:
    cov=pd.DataFrame(np.linalg.inv(f.values),index=f.index,columns=f.columns).iloc[:len(orders),:len(orders)]
    e=[]
    for i,index in enumerate(names):
        e.append(np.sqrt(cov.loc[index,index]))
    err_free.append(np.array(e))
err_free=np.stack(err_free,axis=0)

In [17]:
labels=['CMB','J-PAS ELG','J-PAS LRG','J-PAS QSO','PFS ELG','J-PAS Multitracer','J-PAS Multitracer + PFS ELG','DESI Multitracer','CMB + J-PAS Multitracer\n+ PFS ELG','CMB + DESI Multitracer']
df_free=pd.DataFrame(err_free,index=labels,columns=names)
df_free

,h,omega_m0,omega_b0,sigma_8,n_s,m_nu,N_eff,w0,wa
CMB,0.082834,0.078699,0.012140,0.072504,0.003456,0.149863,0.053177,0.546583,1.522243
J-PAS ELG,0.025591,0.035558,0.008838,0.041079,0.043005,0.452881,0.796763,0.159421,0.837912
J-PAS LRG,0.039352,0.052647,0.012964,0.053528,0.072855,0.603053,1.191640,0.234947,1.155278
J-PAS QSO,0.050989,0.136046,0.028274,0.141264,0.124753,0.752127,2.412090,1.142903,3.384278
PFS ELG,0.046682,0.052053,0.011234,0.107813,0.110339,0.818286,2.542316,0.372194,1.342496
J-PAS Multitracer,0.015843,0.014520,0.004079,0.028620,0.018990,0.310034,0.614888,0.104718,0.473013
J-PAS Multitracer + PFS ELG,0.012695,0.012804,0.003397,0.026745,0.015955,0.283799,0.556329,0.094231,0.408153
DESI Multitracer,0.011568,0.014837,0.003573,0.028232,0.032772,0.276334,0.668068,0.073122,0.362241
CMB + J-PAS Multitracer\n+ PFS ELG,0.002846,0.003038,0.000423,0.005871,0.002270,0.052752,0.035257,0.045439,0.174419
CMB + DESI Multitracer,0.002256,0.002624,0.000330,0.004796,0.002037,0.043835,0.033845,0.029822,0.106966

In [18]:
df_free.to_excel('./numbers/w0wacdm-free.xlsx')

# J-PAS ELG vs. multitracer

In [19]:
data=pd.read_excel('./numbers/lcdm-free.xlsx',header=0,index_col=0)

In [20]:
data.loc['J-PAS ELG']

h           0.019821
omega_m0    0.015171
omega_b0    0.005720
sigma_8     0.034881
n_s         0.026375
m_nu        0.413169
N_eff       0.744878
Name: J-PAS ELG, dtype: float64

In [21]:
data.loc['J-PAS Multitracer']

h           0.012765
omega_m0    0.008393
omega_b0    0.003400
sigma_8     0.025124
n_s         0.016086
m_nu        0.297057
N_eff       0.585492
Name: J-PAS Multitracer, dtype: float64

In [22]:
data.loc['J-PAS ELG']/data.loc['J-PAS Multitracer']

h           1.552786
omega_m0    1.807570
omega_b0    1.682656
sigma_8     1.388355
n_s         1.639650
m_nu        1.390874
N_eff       1.272226
dtype: float64

In [23]:
data=pd.read_excel('./numbers/w0wacdm-free.xlsx',header=0,index_col=0)

In [24]:
data.loc['J-PAS ELG']

h           0.025591
omega_m0    0.035558
omega_b0    0.008838
sigma_8     0.041079
n_s         0.043005
m_nu        0.452881
N_eff       0.796763
w0          0.159421
wa          0.837912
Name: J-PAS ELG, dtype: float64

In [25]:
data.loc['J-PAS Multitracer']

h           0.015843
omega_m0    0.014520
omega_b0    0.004079
sigma_8     0.028620
n_s         0.018990
m_nu        0.310034
N_eff       0.614888
w0          0.104718
wa          0.473013
Name: J-PAS Multitracer, dtype: float64

In [26]:
data.loc['J-PAS ELG']/data.loc['J-PAS Multitracer']

h           1.615311
omega_m0    2.448990
omega_b0    2.166725
sigma_8     1.435328
n_s         2.264681
m_nu        1.460745
N_eff       1.295786
w0          1.522379
wa          1.771435
dtype: float64

# J-PAS ELG + PFS ELG

In [27]:
data=pd.read_excel('./numbers/lcdm-fixed.xlsx',header=0,index_col=0)

In [28]:
data.loc['J-PAS ELG',['h','omega_m0','m_nu']]

h           0.013176
omega_m0    0.014649
m_nu        0.268775
Name: J-PAS ELG, dtype: float64

In [29]:
data.loc['PFS ELG',['h','omega_m0','m_nu']]

h           0.015160
omega_m0    0.013098
m_nu        0.552865
Name: PFS ELG, dtype: float64

In [30]:
JPAS_ELG=var_filter(pd.read_excel('../data/ELG/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
PFS_ELG=var_filter(pd.read_excel('../data/PFS/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)

In [31]:
cov=pd.DataFrame(np.linalg.inv(JPAS_ELG.values),index=JPAS_ELG.index,columns=JPAS_ELG.columns)
JPAS_ELG_marg=np.linalg.inv(cov.iloc[:6,:6].values)

In [32]:
cov=pd.DataFrame(np.linalg.inv(PFS_ELG.values),index=PFS_ELG.index,columns=PFS_ELG.columns)
PFS_ELG_marg=np.linalg.inv(cov.iloc[:6,:6].values)

In [33]:
var_name=['omega_m0','omega_b0','h','n_s','sigma_8','m_nu']
cov_combined=pd.DataFrame(np.linalg.inv(JPAS_ELG_marg+PFS_ELG_marg),index=var_name,columns=var_name)
err=[]
for v in ['h','omega_m0','m_nu']:
    e=np.sqrt(cov_combined.loc[v,v])
    err.append(e)
    print(e)

0.008008537284050078
0.006584988182770667
0.22146200104896216

In [34]:
data.loc['J-PAS ELG',['h','omega_m0','m_nu']]/np.array(err)

h           1.645207
omega_m0    2.224661
m_nu        1.213640
Name: J-PAS ELG, dtype: float64

In [35]:
data.loc['PFS ELG',['h','omega_m0','m_nu']]/np.array(err)

h           1.893042
omega_m0    1.989112
m_nu        2.496432
Name: PFS ELG, dtype: float64

In [36]:
data=pd.read_excel('./numbers/w0wacdm-fixed.xlsx',header=0,index_col=0)

In [37]:
data.loc['J-PAS ELG',['m_nu','w0','wa']]

m_nu    0.296189
w0      0.149992
wa      0.813091
Name: J-PAS ELG, dtype: float64

In [38]:
data.loc['PFS ELG',['m_nu','w0','wa']]

m_nu    0.610892
w0      0.274993
wa      1.065883
Name: PFS ELG, dtype: float64

In [39]:
JPAS_ELG=var_filter(pd.read_excel('../data/ELG/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)
PFS_ELG=var_filter(pd.read_excel('../data/PFS/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=True)

In [40]:
cov=pd.DataFrame(np.linalg.inv(JPAS_ELG.values),index=JPAS_ELG.index,columns=JPAS_ELG.columns)
JPAS_ELG_marg=np.linalg.inv(cov.iloc[:8,:8].values)

In [41]:
cov=pd.DataFrame(np.linalg.inv(PFS_ELG.values),index=PFS_ELG.index,columns=PFS_ELG.columns)
PFS_ELG_marg=np.linalg.inv(cov.iloc[:8,:8].values)

In [42]:
var_name=['omega_m0','omega_b0','h','n_s','sigma_8','m_nu','w0','wa']
cov_combined=pd.DataFrame(np.linalg.inv(JPAS_ELG_marg+PFS_ELG_marg),index=var_name,columns=var_name)
err=[]
for v in ['m_nu','w0','wa']:
    e=np.sqrt(cov_combined.loc[v,v])
    err.append(e)
    print(e)

0.2434743653506088
0.12441459685693493
0.5266346230503607

In [43]:
data.loc['J-PAS ELG',['m_nu','w0','wa']]/np.array(err)

m_nu    1.216510
w0      1.205580
wa      1.543937
Name: J-PAS ELG, dtype: float64

In [44]:
data.loc['PFS ELG',['m_nu','w0','wa']]/np.array(err)

m_nu    2.509061
w0      2.210294
wa      2.023951
Name: PFS ELG, dtype: float64

# CMB + J-PAS Multitracer + PFS ELG vs. CMB

In [45]:
data=pd.read_excel('./numbers/lcdm-free.xlsx',header=0,index_col=0)

In [46]:
data.loc['CMB']

h           0.007932
omega_m0    0.009265
omega_b0    0.001100
sigma_8     0.011241
n_s         0.003306
m_nu        0.051426
N_eff       0.048279
Name: CMB, dtype: float64

In [47]:
data.loc['CMB + J-PAS Multitracer\n+ PFS ELG']

h           0.002139
omega_m0    0.002087
omega_b0    0.000285
sigma_8     0.004055
n_s         0.002043
m_nu        0.017184
N_eff       0.033876
Name: CMB + J-PAS Multitracer\n+ PFS ELG, dtype: float64

In [48]:
data.loc['CMB']/data.loc['CMB + J-PAS Multitracer\n+ PFS ELG']

h           3.707591
omega_m0    4.440033
omega_b0    3.859033
sigma_8     2.771907
n_s         1.617880
m_nu        2.992727
N_eff       1.425145
dtype: float64

In [49]:
data=pd.read_excel('./numbers/w0wacdm-free.xlsx',header=0,index_col=0)

In [50]:
data.loc['CMB']

h           0.082834
omega_m0    0.078699
omega_b0    0.012140
sigma_8     0.072504
n_s         0.003456
m_nu        0.149863
N_eff       0.053177
w0          0.546583
wa          1.522243
Name: CMB, dtype: float64

In [51]:
data.loc['CMB + J-PAS Multitracer\n+ PFS ELG']

h           0.002846
omega_m0    0.003038
omega_b0    0.000423
sigma_8     0.005871
n_s         0.002270
m_nu        0.052752
N_eff       0.035257
w0          0.045439
wa          0.174419
Name: CMB + J-PAS Multitracer\n+ PFS ELG, dtype: float64

In [52]:
data.loc['CMB']/data.loc['CMB + J-PAS Multitracer\n+ PFS ELG']

h           29.102102
omega_m0    25.904515
omega_b0    28.728386
sigma_8     12.350077
n_s          1.522624
m_nu         2.840914
N_eff        1.508241
w0          12.029000
wa           8.727522
dtype: float64