In [1]:
import numpy as np
import pandas as pd
from starfish.plot import *

In [2]:
from starfish.set import settings
settings.cosmo_value

[0.32, 0.049, 0.67, 0.96, 0.81, 0.06, 3.044]

In [3]:
def var_filter(fisher,lcdm,neff_fixed):
    df=fisher.copy()
    if lcdm:
        df=df.drop('w0',axis=0)
        df=df.drop('w0',axis=1)
        df=df.drop('wa',axis=0)
        df=df.drop('wa',axis=1)
    if neff_fixed:
        df=df.drop('N_eff',axis=0)
        df=df.drop('N_eff',axis=1)

    return df

# nuisance parameters of different tracers/surveys should be independent of each other

In [4]:
DESI_multi=var_filter(pd.read_excel('../data/DESI_all/valid.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(DESI_multi.values),index=DESI_multi.index,columns=DESI_multi.columns)
DESI_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

# SO + LiteBIRD + DESI multitracer

In [5]:
cmb_fisher=var_filter(pd.read_excel('../data/CMB/all.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
cmb_fisher

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,tau
omega_m0,2.113157e+08,-7.391461e+08,1.626544e+08,-4.834304e+06,-6.693431e+07,-1.457689e+07,-7.508163e+06,5.208923e+07
omega_b0,-7.391461e+08,2.972795e+09,-5.230892e+08,3.136963e+07,2.383183e+08,5.078972e+07,2.516905e+07,-1.839974e+08
h,1.626544e+08,-5.230892e+08,1.351853e+08,-2.179861e+06,-4.655793e+07,-9.745314e+06,-6.396045e+06,3.626849e+07
n_s,-4.834304e+06,3.136963e+07,-2.179861e+06,1.112812e+06,1.717749e+06,3.189561e+05,1.152375e+05,-1.311012e+06
sigma_8,-6.693431e+07,2.383183e+08,-4.655793e+07,1.717749e+06,2.614606e+07,6.191752e+06,1.849826e+06,-2.031985e+07
m_nu,-1.457689e+07,5.078972e+07,-9.745314e+06,3.189561e+05,6.191752e+06,1.521177e+06,3.498935e+05,-4.837493e+06
N_eff,-7.508163e+06,2.516905e+07,-6.396045e+06,1.152375e+05,1.849826e+06,3.498935e+05,3.262999e+05,-1.436583e+06
tau,5.208923e+07,-1.839974e+08,3.626849e+07,-1.311012e+06,-2.031985e+07,-4.837493e+06,-1.436583e+06,1.613244e+07

In [6]:
cmb_cov=pd.DataFrame(np.linalg.inv(cmb_fisher.values),index=cmb_fisher.index,columns=cmb_fisher.columns)
cmb_cov_marg=cmb_cov.drop('tau',axis=0)
cmb_cov_marg=cmb_cov_marg.drop('tau',axis=1)
cmb_fisher_marg=pd.DataFrame(np.linalg.inv(cmb_cov_marg),index=settings.var_name,columns=settings.var_name)
cmb_fisher_marg

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff
omega_m0,4.312745e+07,-1.450462e+08,4.554887e+07,-6.012452e+05,-1.324571e+06,1.042646e+06,-2.869655e+06
omega_b0,-1.450462e+08,8.742251e+08,-1.094315e+08,1.641698e+07,6.561623e+06,-4.383950e+06,8.784214e+06
h,4.554887e+07,-1.094315e+08,5.364748e+07,7.675169e+05,-8.754294e+05,1.130196e+06,-3.166362e+06
n_s,-6.012452e+05,1.641698e+07,7.675169e+05,1.006272e+06,6.644545e+04,-7.416530e+04,-1.507177e+03
sigma_8,-1.324571e+06,6.561623e+06,-8.754294e+05,6.644545e+04,5.518892e+05,9.861775e+04,4.035742e+04
m_nu,1.042646e+06,-4.383950e+06,1.130196e+06,-7.416530e+04,9.861775e+04,7.060115e+04,-8.088178e+04
N_eff,-2.869655e+06,8.784214e+06,-3.166362e+06,-1.507177e+03,4.035742e+04,-8.088178e+04,1.983733e+05

In [7]:
fisher1_combined=DESI_multi_valid+cmb_fisher_marg
fisher1_combined.to_excel('../data/combined/cmb+dmul-lcdm-free.xlsx')
cov1_combined=pd.DataFrame(np.linalg.inv(fisher1_combined),index=fisher1_combined.index,columns=fisher1_combined.columns)
cov1_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff
omega_m0,3.720705e-06,2.852868e-07,-1.624469e-06,1.893736e-07,-1.954180e-06,0.000019,0.000023
omega_b0,2.852868e-07,4.823644e-08,-3.337576e-07,-2.102360e-07,-4.835905e-07,0.000002,-0.000003
h,-1.624469e-06,-3.337576e-07,2.737298e-06,1.469932e-06,3.679358e-06,-0.000009,0.000031
n_s,1.893736e-07,-2.102360e-07,1.469932e-06,3.676835e-06,1.245224e-06,0.000007,0.000038
sigma_8,-1.954180e-06,-4.835905e-07,3.679358e-06,1.245224e-06,9.381799e-06,-0.000028,0.000039
m_nu,1.894455e-05,1.645466e-06,-9.262686e-06,6.761280e-06,-2.779195e-05,0.000190,0.000136
N_eff,2.337401e-05,-2.577825e-06,3.052946e-05,3.812219e-05,3.876153e-05,0.000136,0.000994

In [8]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 1.9e-03
-- omega_b0: 2.2e-04
--        h: 1.7e-03
--      n_s: 1.9e-03
--  sigma_8: 3.1e-03
--     m_nu: 1.4e-02
--    N_eff: 3.2e-02