In [1]:
import numpy as np
import pandas as pd
from starfish.plot import *

In [2]:
from starfish.set import settings
settings.var_name.remove('N_eff')
settings.cosmo_num-=1

In [3]:
def var_filter(fisher,lcdm,neff_fixed):
    df=fisher.copy()
    if lcdm:
        df=df.drop('w0',axis=0)
        df=df.drop('w0',axis=1)
        df=df.drop('wa',axis=0)
        df=df.drop('wa',axis=1)
    if neff_fixed:
        df=df.drop('N_eff',axis=0)
        df=df.drop('N_eff',axis=1)

    return df

# nuisance parameters of different tracers/surveys should be independent of each other

In [4]:
DESI_multi=var_filter(pd.read_excel('../data/DESI_all/valid.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
cov=pd.DataFrame(np.linalg.inv(DESI_multi.values),index=DESI_multi.index,columns=DESI_multi.columns)
DESI_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [5]:
JPAS_multi=var_filter(pd.read_excel('../data/jpas_all/valid.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
cov=pd.DataFrame(np.linalg.inv(JPAS_multi.values),index=JPAS_multi.index,columns=JPAS_multi.columns)
JPAS_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [6]:
PFS_ELG=var_filter(pd.read_excel('../data/PFS/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
cov=pd.DataFrame(np.linalg.inv(PFS_ELG.values),index=PFS_ELG.index,columns=PFS_ELG.columns)
PFS_ELG_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

# SO + LiteBIRD + DESI multitracer

In [7]:
cmb_fisher=var_filter(pd.read_excel('../data/CMB/all.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=True)
cmb_fisher

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,tau
omega_m0,2.147834e+08,-7.541764e+08,1.650643e+08,-4.990171e+06,-6.793243e+07,-1.477549e+07,5.285179e+07
omega_b0,-7.541764e+08,3.045160e+09,-5.322297e+08,3.220158e+07,2.430377e+08,5.176599e+07,-1.876023e+08
h,1.650643e+08,-5.322297e+08,1.371531e+08,-2.256316e+06,-4.712226e+07,-9.843028e+06,3.669686e+07
n_s,-4.990171e+06,3.220158e+07,-2.256316e+06,1.126557e+06,1.775017e+06,3.317576e+05,-1.355804e+06
sigma_8,-6.793243e+07,2.430377e+08,-4.712226e+07,1.775017e+06,2.652467e+07,6.277010e+06,-2.060786e+07
m_nu,-1.477549e+07,5.176599e+07,-9.843028e+06,3.317576e+05,6.277010e+06,1.541394e+06,-4.902868e+06
tau,5.285179e+07,-1.876023e+08,3.669686e+07,-1.355804e+06,-2.060786e+07,-4.902868e+06,1.635373e+07

In [8]:
cmb_cov=pd.DataFrame(np.linalg.inv(cmb_fisher.values),index=cmb_fisher.index,columns=cmb_fisher.columns)
cmb_cov_marg=cmb_cov.drop('tau',axis=0)
cmb_cov_marg=cmb_cov_marg.drop('tau',axis=1)
cmb_fisher_marg=pd.DataFrame(np.linalg.inv(cmb_cov_marg),index=settings.var_name,columns=settings.var_name)
cmb_fisher_marg

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu
omega_m0,4.397760e+07,-1.478854e+08,4.646782e+07,-6.085000e+05,-1.332188e+06,1.069536e+06
omega_b0,-1.478854e+08,8.930742e+08,-1.112605e+08,1.664844e+07,6.633934e+06,-4.477407e+06
h,4.646782e+07,-1.112605e+08,5.480743e+07,7.860325e+05,-8.793651e+05,1.158735e+06
n_s,-6.085000e+05,1.664844e+07,7.860325e+05,1.014154e+06,6.652502e+04,-7.471398e+04
sigma_8,-1.332188e+06,6.633934e+06,-8.793651e+05,6.652502e+04,5.560451e+05,9.874888e+04
m_nu,1.069536e+06,-4.477407e+06,1.158735e+06,-7.471398e+04,9.874888e+04,7.150858e+04

In [9]:
fisher1_combined=DESI_multi_valid+cmb_fisher_marg
fisher1_combined.to_excel('../data/combined/cmb+dmul-lcdm-fixed.xlsx')
cov1_combined=pd.DataFrame(np.linalg.inv(fisher1_combined),index=fisher1_combined.index,columns=fisher1_combined.columns)
cov1_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu
omega_m0,3.170341e-06,3.458561e-07,-2.342202e-06,-7.060383e-07,-2.866576e-06,0.000016
omega_b0,3.458561e-07,4.146553e-08,-2.547361e-07,-1.104462e-07,-3.825548e-07,0.000002
h,-2.342202e-06,-2.547361e-07,1.798660e-06,3.014268e-07,2.487069e-06,-0.000013
n_s,-7.060383e-07,-1.104462e-07,3.014268e-07,2.194585e-06,-2.314368e-07,0.000001
sigma_8,-2.866576e-06,-3.825548e-07,2.487069e-06,-2.314368e-07,7.824697e-06,-0.000033
m_nu,1.573780e-05,1.997816e-06,-1.344661e-05,1.493972e-06,-3.297468e-05,0.000171

In [10]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 1.8e-03
-- omega_b0: 2.0e-04
--        h: 1.3e-03
--      n_s: 1.5e-03
--  sigma_8: 2.8e-03
--     m_nu: 1.3e-02

# SO + LiteBIRD + DESI multitracer

In [11]:
fisher2=pd.DataFrame(JPAS_multi_valid+PFS_ELG_valid,index=settings.var_name,columns=settings.var_name)
fisher2.to_excel('../data/combined/pelg+jmul-lcdm-fixed.xlsx')

In [12]:
fisher2_combined=JPAS_multi_valid+PFS_ELG_valid+cmb_fisher_marg
fisher2_combined.to_excel('../data/combined/cmb+pelg+jmul-lcdm-fixed.xlsx')
cov2_combined=pd.DataFrame(np.linalg.inv(fisher2_combined),index=fisher2_combined.index,columns=fisher2_combined.columns)
cov2_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu
omega_m0,4.281709e-06,4.954062e-07,-3.227775e-06,-1.126380e-06,-5.171401e-06,2.574004e-05
omega_b0,4.954062e-07,6.126092e-08,-3.756334e-07,-1.519180e-07,-7.058134e-07,3.382630e-06
h,-3.227775e-06,-3.756334e-07,2.507096e-06,6.269171e-07,4.417636e-06,-2.171891e-05
n_s,-1.126380e-06,-1.519180e-07,6.269171e-07,2.185204e-06,1.402201e-07,-6.373978e-07
sigma_8,-5.171401e-06,-7.058134e-07,4.417636e-06,1.402201e-07,1.416330e-05,-5.857914e-05
m_nu,2.574004e-05,3.382630e-06,-2.171891e-05,-6.373978e-07,-5.857914e-05,2.759972e-04

In [13]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov2_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 2.1e-03
-- omega_b0: 2.5e-04
--        h: 1.6e-03
--      n_s: 1.5e-03
--  sigma_8: 3.8e-03
--     m_nu: 1.7e-02