In [1]:
import numpy as np
import pandas as pd
from starfish.plot import *

In [2]:
from starfish.set import settings
settings.cosmo_value

[0.32, 0.049, 0.67, 0.96, 0.81, 0.06, 3.044, -1, 0]

In [3]:
def var_filter(fisher,lcdm,neff_fixed):
    df=fisher.copy()
    if lcdm:
        df=df.drop('w0',axis=0)
        df=df.drop('w0',axis=1)
        df=df.drop('wa',axis=0)
        df=df.drop('wa',axis=1)
    if neff_fixed:
        df=df.drop('N_eff',axis=0)
        df=df.drop('N_eff',axis=1)

    return df

# nuisance parameters of different tracers/surveys should be independent of each other

In [4]:
JPAS_multi=var_filter(pd.read_excel('../data/jpas_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(JPAS_multi.values),index=JPAS_multi.index,columns=JPAS_multi.columns)
JPAS_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [5]:
PFS_ELG=var_filter(pd.read_excel('../data/PFS/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(PFS_ELG.values),index=PFS_ELG.index,columns=PFS_ELG.columns)
PFS_ELG_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

# J-PAS multitracer + PFS ELG

In [6]:
fisher1=pd.DataFrame(JPAS_multi_valid+PFS_ELG_valid,index=settings.var_name,columns=settings.var_name)
fisher1.to_excel('../data/combined/pelg+jmul-w0wacdm-free.xlsx')
fisher1

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,543831.929977,-9.858576e+05,74888.073197,221829.070537,-10062.167937,-22067.404750,-8468.205857,-19574.613427,-1859.913506
omega_b0,-985857.647127,2.505464e+06,-410464.011839,-423082.660153,44839.019530,42500.389546,21380.711460,10982.376326,137.442784
h,74888.073197,-4.104640e+05,285152.296991,48556.944450,-98803.121007,-5392.025981,-4066.114502,16151.809616,5443.117187
n_s,221829.070537,-4.230827e+05,48556.944450,103838.218472,-17728.695611,-10113.712011,-3841.449518,-7218.068523,-727.985857
sigma_8,-10062.167937,4.483902e+04,-98803.121008,-17728.695611,82575.267173,3933.386348,457.330952,-1790.426178,-1869.841147
m_nu,-22067.404750,4.250039e+04,-5392.025981,-10113.712011,3933.386348,1160.792168,371.743250,923.706524,84.400591
N_eff,-8468.205857,2.138071e+04,-4066.114502,-3841.449518,457.330952,371.743250,198.359135,63.607594,-6.059102
w0,-19574.613427,1.098238e+04,16151.809616,-7218.068523,-1790.426178,923.706524,63.607594,3290.396906,655.475685
wa,-1859.913506,1.374428e+02,5443.117187,-727.985857,-1869.841147,84.400591,-6.059102,655.475685,196.195825

In [7]:
cov1=pd.DataFrame(np.linalg.inv(fisher1.values),index=settings.var_name,columns=settings.var_name)
cov1

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,0.000164,0.000026,-0.000044,-0.000146,-0.000236,0.002019,-0.003218,0.001049,-0.004507
omega_b0,0.000026,0.000012,0.000007,-0.000032,-0.000010,-0.000048,-0.000592,0.000189,-0.000809
h,-0.000044,0.000007,0.000161,0.000022,0.000283,-0.002846,0.005799,-0.000136,-0.000255
n_s,-0.000146,-0.000032,0.000022,0.000255,0.000148,-0.000446,0.003495,-0.000929,0.003777
sigma_8,-0.000236,-0.000010,0.000283,0.000148,0.000715,-0.007084,0.011882,-0.001267,0.004936
m_nu,0.002019,-0.000048,-0.002846,-0.000446,-0.007084,0.080542,-0.114024,0.008171,-0.036516
N_eff,-0.003218,-0.000592,0.005799,0.003495,0.011882,-0.114024,0.309502,-0.012701,0.036270
w0,0.001049,0.000189,-0.000136,-0.000929,-0.001267,0.008171,-0.012701,0.008879,-0.035526
wa,-0.004507,-0.000809,-0.000255,0.003777,0.004936,-0.036516,0.036270,-0.035526,0.166589

In [8]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 1.3e-02
-- omega_b0: 3.4e-03
--        h: 1.3e-02
--      n_s: 1.6e-02
--  sigma_8: 2.7e-02
--     m_nu: 2.8e-01
--    N_eff: 5.6e-01
--       w0: 9.4e-02
--       wa: 4.1e-01

# + SO + LiteBIRD

In [9]:
cmb_fisher=var_filter(pd.read_excel('../data/CMB/all.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cmb_fisher

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,tau,w0,wa
omega_m0,2.147834e+08,-7.541764e+08,1.650643e+08,-4.990171e+06,-6.793243e+07,-1.477549e+07,-7.638291e+06,5.285179e+07,1.526209e+06,-43858.240484
omega_b0,-7.541764e+08,3.045160e+09,-5.322297e+08,3.220158e+07,2.430377e+08,5.176599e+07,2.567687e+07,-1.876023e+08,-7.272188e+06,-347201.477824
h,1.650643e+08,-5.322297e+08,1.371531e+08,-2.256316e+06,-4.712226e+07,-9.843028e+06,-6.503294e+06,3.669686e+07,3.577965e+06,651471.937061
n_s,-4.990171e+06,3.220158e+07,-2.256316e+06,1.126557e+06,1.775017e+06,3.317576e+05,1.191634e+05,-1.355804e+06,-1.478760e+05,-28437.056773
sigma_8,-6.793243e+07,2.430377e+08,-4.712226e+07,1.775017e+06,2.652467e+07,6.277010e+06,1.876784e+06,-2.060786e+07,2.218886e+06,778936.336670
m_nu,-1.477549e+07,5.176599e+07,-9.843028e+06,3.317576e+05,6.277010e+06,1.541394e+06,3.540514e+05,-4.902868e+06,7.908602e+05,256559.839365
N_eff,-7.638291e+06,2.567687e+07,-6.503294e+06,1.191634e+05,1.876784e+06,3.540514e+05,3.324630e+05,-1.457025e+06,-3.412282e+05,-79794.086125
tau,5.285179e+07,-1.876023e+08,3.669686e+07,-1.355804e+06,-2.060786e+07,-4.902868e+06,-1.457025e+06,1.635373e+07,-1.773297e+06,-619360.547727
w0,1.526209e+06,-7.272188e+06,3.577965e+06,-1.478760e+05,2.218886e+06,7.908602e+05,-3.412282e+05,-1.773297e+06,1.552171e+06,435641.832226
wa,-4.385824e+04,-3.472015e+05,6.514719e+05,-2.843706e+04,7.789363e+05,2.565598e+05,-7.979409e+04,-6.193605e+05,4.356418e+05,123324.164109

In [10]:
cmb_cov=pd.DataFrame(np.linalg.inv(cmb_fisher.values),index=cmb_fisher.index,columns=cmb_fisher.columns)
cmb_cov_marg=cmb_cov.drop('tau',axis=0)
cmb_cov_marg=cmb_cov_marg.drop('tau',axis=1)
cmb_fisher_marg=pd.DataFrame(np.linalg.inv(cmb_cov_marg),index=settings.var_name,columns=settings.var_name)
cmb_fisher_marg

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,4.397760e+07,-1.478854e+08,4.646782e+07,-6.085000e+05,-1.332188e+06,1.069536e+06,-2.929495e+06,7.257129e+06,1.957784e+06
omega_b0,-1.478854e+08,8.930742e+08,-1.112605e+08,1.664844e+07,6.633934e+06,-4.477407e+06,8.962561e+06,-2.761462e+07,-7.452216e+06
h,4.646782e+07,-1.112605e+08,5.480743e+07,7.860325e+05,-8.793651e+05,1.158735e+06,-3.233810e+06,7.557145e+06,2.041283e+06
n_s,-6.085000e+05,1.664844e+07,7.860325e+05,1.014154e+06,6.652502e+04,-7.471398e+04,-1.631060e+03,-2.948910e+05,-7.978507e+04
sigma_8,-1.332188e+06,6.633934e+06,-8.793651e+05,6.652502e+04,5.560451e+05,9.874888e+04,4.073989e+04,-1.570282e+04,-1.539849e+03
m_nu,1.069536e+06,-4.477407e+06,1.158735e+06,-7.471398e+04,9.874888e+04,7.150858e+04,-8.276648e+04,2.592236e+05,7.087480e+04
N_eff,-2.929495e+06,8.962561e+06,-3.233810e+06,-1.631060e+03,4.073989e+04,-8.276648e+04,2.026503e+05,-4.992189e+05,-1.349756e+05
w0,7.257129e+06,-2.761462e+07,7.557145e+06,-2.948910e+05,-1.570282e+04,2.592236e+05,-4.992189e+05,1.359885e+06,3.684822e+05
wa,1.957784e+06,-7.452216e+06,2.041283e+06,-7.978507e+04,-1.539849e+03,7.087480e+04,-1.349756e+05,3.684822e+05,9.986728e+04

In [11]:
df=pd.DataFrame(np.linalg.inv(cmb_fisher_marg.values),index=cmb_fisher_marg.index,columns=cmb_fisher_marg.columns)
np.sqrt((df.loc['w0','w0'],df.loc['wa','wa']))

array([0.53830182, 1.50348762])

In [12]:
fisher1_combined=fisher1+cmb_fisher_marg
fisher1_combined.to_excel('../data/combined/cmb+pelg+jmul-w0wacdm-free.xlsx')
cov1_combined=pd.DataFrame(np.linalg.inv(fisher1_combined),index=fisher1_combined.index,columns=fisher1_combined.columns)
cov1_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,9.178582e-06,7.934584e-07,-4.867762e-06,-9.068517e-08,-0.000014,0.000101,0.000026,0.000088,-0.000382
omega_b0,7.934584e-07,1.776905e-07,-1.157756e-06,-4.283266e-08,-0.000001,-0.000002,-0.000002,0.000012,-0.000024
h,-4.867762e-06,-1.157756e-06,8.077773e-06,7.742453e-07,0.000009,0.000012,0.000032,-0.000071,0.000142
n_s,-9.068517e-08,-4.283266e-08,7.742453e-07,5.133372e-06,0.000001,-0.000018,0.000054,0.000033,-0.000049
sigma_8,-1.404796e-05,-1.331658e-06,8.918286e-06,1.161810e-06,0.000034,-0.000221,0.000013,-0.000151,0.000728
m_nu,1.013512e-04,-1.881053e-06,1.246591e-05,-1.841429e-05,-0.000221,0.002762,0.000201,0.000573,-0.006199
N_eff,2.571543e-05,-1.997640e-06,3.214117e-05,5.415625e-05,0.000013,0.000201,0.001225,0.000434,-0.001357
w0,8.767989e-05,1.183808e-05,-7.134503e-05,3.296483e-05,-0.000151,0.000573,0.000434,0.002055,-0.006754
wa,-3.819431e-04,-2.370707e-05,1.423405e-04,-4.857936e-05,0.000728,-0.006199,-0.001357,-0.006754,0.030265

In [13]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 3.0e-03
-- omega_b0: 4.2e-04
--        h: 2.8e-03
--      n_s: 2.3e-03
--  sigma_8: 5.8e-03
--     m_nu: 5.3e-02
--    N_eff: 3.5e-02
--       w0: 4.5e-02
--       wa: 1.7e-01

# SO + LiteBIRD + PFS

In [14]:
PFS_combined=PFS_ELG_valid+cmb_fisher_marg
PFS_combined.to_excel('../data/combined/cmb+pelg-w0wacdm-free.xlsx')
cov_combined=pd.DataFrame(np.linalg.inv(PFS_combined),index=PFS_combined.index,columns=PFS_combined.columns)
cov_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,3.025541e-05,3.865231e-06,-2.574228e-05,6.705825e-07,-0.000030,0.000090,4.660674e-05,0.000166,-0.000393
omega_b0,3.865231e-06,6.637962e-07,-4.445664e-06,1.185274e-07,-0.000004,-0.000008,5.253504e-07,0.000024,-0.000018
h,-2.574228e-05,-4.445664e-06,3.042058e-05,2.929783e-07,0.000026,0.000043,2.309774e-05,-0.000153,0.000116
n_s,6.705825e-07,1.185274e-07,2.929783e-07,9.129183e-06,0.000005,-0.000066,1.080311e-04,0.000040,0.000041
sigma_8,-3.049223e-05,-3.802314e-06,2.623837e-05,4.528111e-06,0.000058,-0.000292,6.532505e-05,-0.000249,0.000996
m_nu,9.024009e-05,-7.528306e-06,4.335384e-05,-6.552623e-05,-0.000292,0.003914,-3.958430e-04,0.000698,-0.009160
N_eff,4.660674e-05,5.253504e-07,2.309774e-05,1.080311e-04,0.000065,-0.000396,2.018126e-03,0.000498,-0.000090
w0,1.663907e-04,2.412191e-05,-1.529903e-04,4.012571e-05,-0.000249,0.000698,4.983890e-04,0.002973,-0.009096
wa,-3.931917e-04,-1.825554e-05,1.164796e-04,4.148445e-05,0.000996,-0.009160,-9.021743e-05,-0.009096,0.043953

In [15]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 5.5e-03
-- omega_b0: 8.1e-04
--        h: 5.5e-03
--      n_s: 3.0e-03
--  sigma_8: 7.6e-03
--     m_nu: 6.3e-02
--    N_eff: 4.5e-02
--       w0: 5.5e-02
--       wa: 2.1e-01