In [1]:
import numpy as np
import pandas as pd
from starfish.plot import *

In [2]:
from starfish.set import settings
settings.cosmo_value

[0.32, 0.049, 0.67, 0.96, 0.81, 0.06, 3.044, -0.758, -0.82]

In [3]:
def var_filter(fisher,lcdm,neff_fixed):
    df=fisher.copy()
    if lcdm:
        df=df.drop('w0',axis=0)
        df=df.drop('w0',axis=1)
        df=df.drop('wa',axis=0)
        df=df.drop('wa',axis=1)
    if neff_fixed:
        df=df.drop('N_eff',axis=0)
        df=df.drop('N_eff',axis=1)

    return df

# nuisance parameters of different tracers/surveys should be independent of each other

In [4]:
JPAS_multi=var_filter(pd.read_excel('../data/jpas_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(JPAS_multi.values),index=JPAS_multi.index,columns=JPAS_multi.columns)
JPAS_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [5]:
DESI_multi=var_filter(pd.read_excel('../data/DESI_all/valid.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(DESI_multi.values),index=DESI_multi.index,columns=DESI_multi.columns)
DESI_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [6]:
PFS_ELG=var_filter(pd.read_excel('../data/PFS/fisher.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(PFS_ELG.values),index=PFS_ELG.index,columns=PFS_ELG.columns)
PFS_ELG_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [7]:
cmb_fisher=var_filter(pd.read_excel('../data/CMB/all.xlsx',header=0,index_col=0),lcdm=False,neff_fixed=False)
cmb_fisher

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,tau,w0,wa
omega_m0,2.090515e+08,-7.355878e+08,1.615557e+08,-4.852491e+06,-6.647323e+07,-1.446175e+07,-7.463214e+06,5.170784e+07,2.054003e+06,2.273677e+05
omega_b0,-7.355878e+08,2.976210e+09,-5.220868e+08,3.155801e+07,2.386367e+08,5.085655e+07,2.511029e+07,-1.841453e+08,-8.875519e+06,-1.198113e+06
h,1.615557e+08,-5.220868e+08,1.346329e+08,-2.200936e+06,-4.648792e+07,-9.733573e+06,-6.367158e+06,3.620245e+07,3.644956e+06,7.094489e+05
n_s,-4.852491e+06,3.155801e+07,-2.200936e+06,1.114652e+06,1.735298e+06,3.227208e+05,1.160810e+05,-1.322969e+06,-1.549119e+05,-3.137197e+04
sigma_8,-6.647323e+07,2.386367e+08,-4.648792e+07,1.735298e+06,2.614180e+07,6.187153e+06,1.847552e+06,-2.030777e+07,1.761388e+06,5.508438e+05
m_nu,-1.446175e+07,5.085655e+07,-9.733573e+06,3.227208e+05,6.187153e+06,1.519000e+06,3.497816e+05,-4.832063e+06,6.566512e+05,1.902996e+05
N_eff,-7.463214e+06,2.511029e+07,-6.367158e+06,1.160810e+05,1.847552e+06,3.497816e+05,3.246830e+05,-1.434322e+06,-3.245819e+05,-7.302010e+04
tau,5.170784e+07,-1.841453e+08,3.620245e+07,-1.322969e+06,-2.030777e+07,-4.832063e+06,-1.434322e+06,1.611478e+07,-1.412284e+06,-4.393529e+05
w0,2.054003e+06,-8.875519e+06,3.644956e+06,-1.549119e+05,1.761388e+06,6.566512e+05,-3.245819e+05,-1.412284e+06,1.261488e+06,3.222435e+05
wa,2.273677e+05,-1.198113e+06,7.094489e+05,-3.137197e+04,5.508438e+05,1.902996e+05,-7.302010e+04,-4.393529e+05,3.222435e+05,8.274964e+04

In [8]:
cmb_cov=pd.DataFrame(np.linalg.inv(cmb_fisher.values),index=cmb_fisher.index,columns=cmb_fisher.columns)
cmb_cov_marg=cmb_cov.drop('tau',axis=0)
cmb_cov_marg=cmb_cov_marg.drop('tau',axis=1)
cmb_fisher_marg=pd.DataFrame(np.linalg.inv(cmb_cov_marg),index=settings.var_name,columns=settings.var_name)
cmb_fisher_marg

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,4.313548e+07,-1.447169e+08,4.539212e+07,-6.074511e+05,-1.311272e+06,1.042994e+06,-2.860873e+06,6.585630e+06,1.637129e+06
omega_b0,-1.447169e+08,8.719625e+08,-1.083976e+08,1.644030e+07,6.577796e+06,-4.359934e+06,8.720136e+06,-2.501384e+07,-6.218645e+06
h,4.539212e+07,-1.083976e+08,5.330279e+07,7.711633e+05,-8.657728e+05,1.121836e+06,-3.144900e+06,6.817705e+06,1.696472e+06
n_s,-6.074511e+05,1.644030e+07,7.711633e+05,1.006040e+06,6.809873e+04,-7.397533e+04,-1.672094e+03,-2.708556e+05,-6.744136e+04
sigma_8,-1.311272e+06,6.577796e+06,-8.657728e+05,6.809873e+04,5.500617e+05,9.781173e+04,4.002579e+04,-1.836541e+04,-2.826530e+03
m_nu,1.042994e+06,-4.359934e+06,1.121836e+06,-7.397533e+04,9.781173e+04,7.009247e+04,-8.030412e+04,2.331738e+05,5.855836e+04
N_eff,-2.860873e+06,8.720136e+06,-3.144900e+06,-1.672094e+03,4.002579e+04,-8.030412e+04,1.970188e+05,-4.502846e+05,-1.121254e+05
w0,6.585630e+06,-2.501384e+07,6.817705e+06,-2.708556e+05,-1.836541e+04,2.331738e+05,-4.502846e+05,1.137717e+06,2.837390e+05
wa,1.637129e+06,-6.218645e+06,1.696472e+06,-6.744136e+04,-2.826530e+03,5.855836e+04,-1.121254e+05,2.837390e+05,7.077114e+04

# SO + LiteBIRD + J-PAS multitracer + PFS ELG

In [9]:
fisher1=pd.DataFrame(JPAS_multi_valid+PFS_ELG_valid,index=settings.var_name,columns=settings.var_name)
fisher1.to_excel('../data/combined/pelg+jmul-w0wacdm-free.xlsx')
cov1=pd.DataFrame(np.linalg.inv(fisher1.values),index=settings.var_name,columns=settings.var_name)

In [10]:
fisher1_combined=fisher1+cmb_fisher_marg
fisher1_combined.to_excel('../data/combined/cmb+pelg+jmul-w0wacdm-free.xlsx')
cov1_combined=pd.DataFrame(np.linalg.inv(fisher1_combined),index=fisher1_combined.index,columns=fisher1_combined.columns)
cov1_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,7.620024e-06,7.909407e-07,-4.791807e-06,1.639410e-07,-1.081848e-05,0.000061,0.000025,0.000078,-0.000317
omega_b0,7.909407e-07,1.777378e-07,-1.160008e-06,-6.394764e-08,-1.313075e-06,-0.000002,-0.000002,0.000011,-0.000020
h,-4.791807e-06,-1.160008e-06,8.125680e-06,9.214482e-07,8.697627e-06,0.000015,0.000034,-0.000064,0.000115
n_s,1.639411e-07,-6.394764e-08,9.214482e-07,5.122640e-06,6.793214e-07,-0.000010,0.000056,0.000032,-0.000058
sigma_8,-1.081848e-05,-1.313075e-06,8.697627e-06,6.793214e-07,2.775631e-05,-0.000141,0.000017,-0.000133,0.000604
m_nu,6.066003e-05,-2.011584e-06,1.471940e-05,-1.039278e-05,-1.414451e-04,0.001744,0.000181,0.000413,-0.004757
N_eff,2.489761e-05,-2.222544e-06,3.441446e-05,5.568165e-05,1.664982e-05,0.000181,0.001265,0.000445,-0.001475
w0,7.837821e-05,1.087373e-05,-6.429037e-05,3.198134e-05,-1.328135e-04,0.000413,0.000445,0.001964,-0.006798
wa,-3.168266e-04,-2.041225e-05,1.152580e-04,-5.812414e-05,6.035871e-04,-0.004757,-0.001475,-0.006798,0.031592

In [11]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 2.8e-03
-- omega_b0: 4.2e-04
--        h: 2.9e-03
--      n_s: 2.3e-03
--  sigma_8: 5.3e-03
--     m_nu: 4.2e-02
--    N_eff: 3.6e-02
--       w0: 4.4e-02
--       wa: 1.8e-01

# SO + LiteBIRD + DESI multitracer

In [12]:
DESI_combined=DESI_multi_valid+cmb_fisher_marg
DESI_combined.to_excel('../data/combined/cmb+dmul-w0wacdm-free.xlsx')
covd_combined=pd.DataFrame(np.linalg.inv(DESI_combined),index=DESI_combined.index,columns=DESI_combined.columns)
covd_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,w0,wa
omega_m0,6.013829e-06,4.767932e-07,-2.543126e-06,1.220592e-06,-6.425695e-06,0.000045,0.000043,0.000039,-0.000159
omega_b0,4.767932e-07,1.081874e-07,-7.084201e-07,-7.225925e-08,-6.921889e-07,-0.000002,-0.000002,0.000006,-0.000010
h,-2.543126e-06,-7.084201e-07,5.129558e-06,7.194149e-07,4.355823e-06,0.000018,0.000028,-0.000035,0.000044
n_s,1.220592e-06,-7.225925e-08,7.194149e-07,4.291015e-06,-4.834765e-07,0.000011,0.000047,0.000021,-0.000066
sigma_8,-6.425695e-06,-6.921889e-07,4.355823e-06,-4.834765e-07,1.904005e-05,-0.000102,-0.000002,-0.000063,0.000317
m_nu,4.517861e-05,-1.686000e-06,1.759799e-05,1.128575e-05,-1.020033e-04,0.001201,0.000449,0.000076,-0.002190
N_eff,4.344825e-05,-1.657478e-06,2.786268e-05,4.747776e-05,-1.850702e-06,0.000449,0.001201,0.000296,-0.001431
w0,3.885335e-05,6.099979e-06,-3.487258e-05,2.084741e-05,-6.304938e-05,0.000076,0.000296,0.000811,-0.002351
wa,-1.593465e-04,-1.031251e-05,4.373389e-05,-6.568697e-05,3.174974e-04,-0.002190,-0.001431,-0.002351,0.010647

In [13]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(covd_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 2.5e-03
-- omega_b0: 3.3e-04
--        h: 2.3e-03
--      n_s: 2.1e-03
--  sigma_8: 4.4e-03
--     m_nu: 3.5e-02
--    N_eff: 3.5e-02
--       w0: 2.8e-02
--       wa: 1.0e-01