In [1]:
import numpy as np
import pandas as pd
from starfish.plot import *

In [2]:
from starfish.set import settings
settings.cosmo_value

[0.32, 0.049, 0.67, 0.96, 0.81, 0.06, 3.044]

In [3]:
def var_filter(fisher,lcdm,neff_fixed):
    df=fisher.copy()
    if lcdm:
        df=df.drop('w0',axis=0)
        df=df.drop('w0',axis=1)
        df=df.drop('wa',axis=0)
        df=df.drop('wa',axis=1)
    if neff_fixed:
        df=df.drop('N_eff',axis=0)
        df=df.drop('N_eff',axis=1)

    return df

# nuisance parameters of different tracers/surveys should be independent of each other

In [4]:
JPAS_multi=var_filter(pd.read_excel('../data/jpas_all/valid.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(JPAS_multi.values),index=JPAS_multi.index,columns=JPAS_multi.columns)
JPAS_multi_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

In [5]:
PFS_ELG=var_filter(pd.read_excel('../data/PFS/fisher.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
cov=pd.DataFrame(np.linalg.inv(PFS_ELG.values),index=PFS_ELG.index,columns=PFS_ELG.columns)
PFS_ELG_valid=np.linalg.inv(cov.iloc[:settings.cosmo_num,:settings.cosmo_num].values)

# J-PAS multitracer + PFS ELG

In [6]:
fisher1=pd.DataFrame(JPAS_multi_valid+PFS_ELG_valid,index=settings.var_name,columns=settings.var_name)
fisher1.to_excel('../data/combined/pelg+jmul-lcdm-free.xlsx')
fisher1

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff
omega_m0,543831.929977,-9.858576e+05,74888.073197,221829.070537,-10062.167937,-22067.404750,-8468.205857
omega_b0,-985857.647127,2.505464e+06,-410464.011839,-423082.660153,44839.019530,42500.389546,21380.711460
h,74888.073197,-4.104640e+05,285152.296991,48556.944450,-98803.121007,-5392.025981,-4066.114502
n_s,221829.070537,-4.230827e+05,48556.944450,103838.218472,-17728.695611,-10113.712011,-3841.449518
sigma_8,-10062.167937,4.483902e+04,-98803.121007,-17728.695611,82575.267173,3933.386348,457.330952
m_nu,-22067.404750,4.250039e+04,-5392.025981,-10113.712011,3933.386348,1160.792168,371.743250
N_eff,-8468.205857,2.138071e+04,-4066.114502,-3841.449518,457.330952,371.743250,198.359135

In [7]:
cov1=pd.DataFrame(np.linalg.inv(fisher1.values),index=settings.var_name,columns=settings.var_name)
cov1

          omega_m0  omega_b0         h       n_s   sigma_8      m_nu     N_eff
omega_m0  0.000036  0.000003 -0.000038 -0.000036 -0.000088  0.001005 -0.001902
omega_b0  0.000003  0.000007  0.000008 -0.000012  0.000017 -0.000230 -0.000353
h        -0.000038  0.000008  0.000133  0.000010  0.000259 -0.002846  0.005131
n_s      -0.000036 -0.000012  0.000010  0.000157  0.000016  0.000418  0.002202
sigma_8  -0.000088  0.000017  0.000259  0.000016  0.000534 -0.005938  0.009989
m_nu      0.001005 -0.000230 -0.002846  0.000418 -0.005938  0.072424 -0.104611
N_eff    -0.001902 -0.000353  0.005131  0.002202  0.009989 -0.104611  0.282681

In [8]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 6.0e-03
-- omega_b0: 2.7e-03
--        h: 1.2e-02
--      n_s: 1.3e-02
--  sigma_8: 2.3e-02
--     m_nu: 2.7e-01
--    N_eff: 5.3e-01

# + SO + LiteBIRD

In [9]:
cmb_fisher=var_filter(pd.read_excel('../data/CMB/all.xlsx',header=0,index_col=0),lcdm=True,neff_fixed=False)
cmb_fisher

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff,tau
omega_m0,2.147834e+08,-7.541764e+08,1.650643e+08,-4.990171e+06,-6.793243e+07,-1.477549e+07,-7.638291e+06,5.285179e+07
omega_b0,-7.541764e+08,3.045160e+09,-5.322297e+08,3.220158e+07,2.430377e+08,5.176599e+07,2.567687e+07,-1.876023e+08
h,1.650643e+08,-5.322297e+08,1.371531e+08,-2.256316e+06,-4.712226e+07,-9.843028e+06,-6.503294e+06,3.669686e+07
n_s,-4.990171e+06,3.220158e+07,-2.256316e+06,1.126557e+06,1.775017e+06,3.317576e+05,1.191634e+05,-1.355804e+06
sigma_8,-6.793243e+07,2.430377e+08,-4.712226e+07,1.775017e+06,2.652467e+07,6.277010e+06,1.876784e+06,-2.060786e+07
m_nu,-1.477549e+07,5.176599e+07,-9.843028e+06,3.317576e+05,6.277010e+06,1.541394e+06,3.540514e+05,-4.902868e+06
N_eff,-7.638291e+06,2.567687e+07,-6.503294e+06,1.191634e+05,1.876784e+06,3.540514e+05,3.324630e+05,-1.457025e+06
tau,5.285179e+07,-1.876023e+08,3.669686e+07,-1.355804e+06,-2.060786e+07,-4.902868e+06,-1.457025e+06,1.635373e+07

In [10]:
cmb_cov=pd.DataFrame(np.linalg.inv(cmb_fisher.values),index=cmb_fisher.index,columns=cmb_fisher.columns)
cmb_cov_marg=cmb_cov.drop('tau',axis=0)
cmb_cov_marg=cmb_cov_marg.drop('tau',axis=1)
cmb_fisher_marg=pd.DataFrame(np.linalg.inv(cmb_cov_marg),index=settings.var_name,columns=settings.var_name)
cmb_fisher_marg

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff
omega_m0,4.397760e+07,-1.478854e+08,4.646782e+07,-6.085000e+05,-1.332188e+06,1.069536e+06,-2.929495e+06
omega_b0,-1.478854e+08,8.930742e+08,-1.112605e+08,1.664844e+07,6.633934e+06,-4.477407e+06,8.962561e+06
h,4.646782e+07,-1.112605e+08,5.480743e+07,7.860325e+05,-8.793651e+05,1.158735e+06,-3.233810e+06
n_s,-6.085000e+05,1.664844e+07,7.860325e+05,1.014154e+06,6.652502e+04,-7.471398e+04,-1.631060e+03
sigma_8,-1.332188e+06,6.633934e+06,-8.793651e+05,6.652502e+04,5.560451e+05,9.874888e+04,4.073989e+04
m_nu,1.069536e+06,-4.477407e+06,1.158735e+06,-7.471398e+04,9.874888e+04,7.150858e+04,-8.276648e+04
N_eff,-2.929495e+06,8.962561e+06,-3.233810e+06,-1.631060e+03,4.073989e+04,-8.276648e+04,2.026503e+05

In [11]:
fisher1_combined=fisher1+cmb_fisher_marg
fisher1_combined.to_excel('../data/combined/cmb+pelg+jmul-lcdm-free.xlsx')
cov1_combined=pd.DataFrame(np.linalg.inv(fisher1_combined),index=fisher1_combined.index,columns=fisher1_combined.columns)
cov1_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff
omega_m0,4.347504e-06,4.650511e-07,-2.894765e-06,-8.024993e-07,-4.913361e-06,0.000027,0.000008
omega_b0,4.650511e-07,8.089655e-08,-5.733950e-07,-3.451969e-07,-8.954734e-07,0.000003,-0.000005
h,-2.894765e-06,-5.733950e-07,4.549870e-06,2.600482e-06,6.304847e-06,-0.000017,0.000048
n_s,-8.024993e-07,-3.451969e-07,2.600482e-06,4.162312e-06,1.877560e-06,0.000004,0.000047
sigma_8,-4.913361e-06,-8.954734e-07,6.304847e-06,1.877560e-06,1.625509e-05,-0.000056,0.000043
m_nu,2.673539e-05,2.946221e-06,-1.691337e-05,4.353838e-06,-5.555189e-05,0.000293,0.000117
N_eff,8.000071e-06,-4.630516e-06,4.801346e-05,4.667378e-05,4.331973e-05,0.000117,0.001132

In [12]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov1_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 2.1e-03
-- omega_b0: 2.8e-04
--        h: 2.1e-03
--      n_s: 2.0e-03
--  sigma_8: 4.0e-03
--     m_nu: 1.7e-02
--    N_eff: 3.4e-02

# SO + LiteBIRD + PFS

In [13]:
PFS_combined=PFS_ELG_valid+cmb_fisher_marg
PFS_combined.to_excel('../data/combined/cmb+pelg-lcdm-free.xlsx')
cov_combined=pd.DataFrame(np.linalg.inv(PFS_combined),index=PFS_combined.index,columns=PFS_combined.columns)
cov_combined

,omega_m0,omega_b0,h,n_s,sigma_8,m_nu,N_eff
omega_m0,0.000020,2.111184e-06,-0.000015,-2.762440e-06,-0.000018,0.000101,0.000008
omega_b0,0.000002,2.744237e-07,-0.000002,-7.624261e-07,-0.000003,0.000011,-0.000008
h,-0.000015,-1.970343e-06,0.000015,5.836363e-06,0.000018,-0.000073,0.000076
n_s,-0.000003,-7.624261e-07,0.000006,6.809592e-06,0.000005,-0.000004,0.000084
sigma_8,-0.000018,-2.552359e-06,0.000018,5.427655e-06,0.000033,-0.000129,0.000080
m_nu,0.000101,1.094512e-05,-0.000073,-3.641964e-06,-0.000129,0.000683,0.000115
N_eff,0.000008,-8.078096e-06,0.000076,8.434864e-05,0.000080,0.000115,0.001727

In [14]:
name_width=max([len(v) for v in settings.var_name])
error_dict=dict(zip(settings.var_name,np.sqrt(np.diag(cov_combined.values))))
print('1-sigma errors:')
for key in error_dict.keys():
    print(f'-- {key.rjust(name_width)}: {error_dict[key]:.1e}')

1-sigma errors:
-- omega_m0: 4.5e-03
-- omega_b0: 5.2e-04
--        h: 3.8e-03
--      n_s: 2.6e-03
--  sigma_8: 5.7e-03
--     m_nu: 2.6e-02
--    N_eff: 4.2e-02